// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SSSSProject.Models
{
    public partial class Keywords
    {
        public int? KeywordsId { get; set; }

        public List<string>? KeywordsName { get; set; }
        public List<string>? KeywordsType { get; set; }
        public List<string>? KeywordsSex { get; set; }
        public List<string>? KeywordsColor { get; set; }
    }
}