// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SSSSProject.Models
{
    public partial class ProductDetail
    {
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public string ProductSex { get; set; }
        public string ProductColor { get; set; }
        public string ProductPicture { get; set; }
    }
}